# action.yml
name: "Atlas broker testing"
description: "uses for preparing environments for testing"
inputs:
  cf_url:
    description: "PCF url uses for pcf command"
    required: true
  cf_user:
    description: "PCF user uses for pcf command"
    required: true
  cf_password:
    description: "PCF password uses for pcf command"
    required: true
  atlas_project_id:
    description: "for now we should provide our working projectID/groupID in Atlas"
    required: true
  atlas_project_id_bay:
    description: "for now we should provide our working projectID/groupID in Atlas"
    required: false
  atlas_public_key:
    description: "public key for our working projectID/groupID"
    required: true
  atlas_private_key:
    description: "private key for our working projectID/groupID"
    required: true
  credhub_file:
    description: "sample credhub config file"
    required: true
  atlas_org_id:
    description: "atlas org id"
    required: true
  sentry_dsn:
    description: "sentry DSN for telemetry"
    required: true
outputs:
  app_url:
    description: "Application url"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.cf_user }}
    - ${{ inputs.cf_password }}
    - ${{ inputs.cf_url }}
    - ${{ inputs.atlas_project_id }}
    - ${{ inputs.atlas_project_id_bay }}
    - ${{ inputs.atlas_public_key }}
    - ${{ inputs.atlas_private_key }}
    - ${{ inputs.credhub_file }}
    - ${{ inputs.atlas_org_id }}
    - ${{ inputs.sentry_dsn }}
