linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - gochecknoinits
    - gochecknoglobals
    - gocritic
    - gocyclo
    - gofumpt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nlreturn
    - nolintlint
    - noctx
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wrapcheck
issues:
  exclude-rules:
    - path: test
      linters:
        - gocyclo
        - gochecknoglobals
        - wrapcheck
        - nlreturn
    - path: main.go
      linters:
        - gochecknoglobals
        - wrapcheck
  max-issues-per-linter: 0
  max-same-issues: 0