apiVersion: v1
kind: Secret
metadata:
  name: atlas-service-broker-auth
type: Opaque
stringData:
  username: "username"
  password: "password"

---
apiVersion: v1
kind: Secret
metadata:
  name: atlas-auth
type: Opaque
stringData:
  apikeys.json: "
  {
    \"broker\": {
      \"username\": \"username\",
      \"password\": \"password\"
    },
    \"keys\": {
      \"testKey\": {
        \"orgID\" :\"OrgID\",
        \"publicKey\": \"publicKey\",
        \"privateKey\":\"privateKey\"
      }
    }
  }"