name: 'Prepare creds'
description: 'tests'
inputs:
  cf_url:
    description: "PCF url uses for cf command"
    required: true
  cf_user:
    description: "PCF user uses for cf command"
    required: true
  cf_password:
    description: "PCF password uses for cf command"
    required: true

outputs:
  cf_app_url:
    description: "Application CF API URL"
  cf_app_user:
    description: "Application CF username"
  cf_app_password:
    description: "Application CF password"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cf_user }}
    - ${{ inputs.cf_password }}
    - ${{ inputs.cf_url }}
