apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    product: {{ .Chart.Name }}
spec:
  instanceRef:
    name: {{ .Release.Name }}